# ExcellentCaseExpert 配置文件

# AI 模型配置
ai_model:
  provider: "openai"  # 可选: openai, qwen, deepseek, custom
  api_key: "${OPENAI_API_KEY}"  # 支持环境变量，或直接填写 API Key
  base_url: "https://api.openai.com/v1"
  model_name: "gpt-4o-mini"
  max_tokens: 2000
  temperature: 0.7

# OCR 配置
ocr:
  use_paddle_ocr: true
  use_tesseract: true
  languages: ["ch_sim", "en"]
  max_file_size_mb: 50

# 性能配置
performance:
  max_concurrent_tasks: 3
  memory_cleanup_interval: 30
  max_memory_mb: 1024

# UI 配置
ui:
  theme: "light"  # 可选: light, dark, auto
  language: "zh_CN"  # 可选: zh_CN, en_US
  window_width: 1200
  window_height: 800
